# RGBLED widget
CONFIG_RGBLED_WIDGET_BATTERY_SHOW_ONLY_PERIPHERALS=y
CONFIG_RGBLED_WIDGET_CONN_SHOW_USB=n
CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y
CONFIG_RGBLED_WIDGET_LAYER_DEBOUNCE_MS=500

# win
CONFIG_RGBLED_WIDGET_LAYER_1_COLOR=4 

# num
CONFIG_RGBLED_WIDGET_LAYER_2_COLOR=6 

# fun
CONFIG_RGBLED_WIDGET_LAYER_4_COLOR=2 

# battery printer
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
